version: 0.0
os: linux
files:
  - source: build/
    destination: /var/www/html
    overwrite: yes

hooks:
  BeforeInstall:
    - location: sample_video_players_new/scripts/clean_old_files.sh
      timeout: 60
      runas: root

  AfterInstall:
    - location: sample_video_players_new/scripts/copy_build_files.sh
      timeout: 60
      runas: ec2-user
